### ISSUE TITLE
Status of the API

### ISSUE THREAD

**Issue by kjbrum** [joshua-arts/rocket-league-esports-api#1]
I tried testing [the API](https://rocket-league-esports-api.herokuapp.com/graphiql) and I keep getting the following error:
```
SyntaxError: Unexpected token < in JSON at position 0
```

Does this API not work any longer?

**Comment by Bl4CkGuuN** [comment]
The API was using the database from parallel.gg, the site is offline.

**Comment by joshua-arts** [comment]
Yeah, unfortunately all the data that this API was built on is no longer accessible. Along with that, the project is really out-dated and was never really built to be used for anything, but more so as a fun learning project. I'll add some info to the README to better clarify this.

**Comment by kjbrum** [comment]
Bummer, thanks for the update.
